### ISSUE TITLE
Add node .12 and io.js to the CIs

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1054]
.12 is stable and there is a reports of unstable iojs being more stable then .12.

Yeah, travis and appveyor does support them.

**Comment by hzoo** [comment]
We can also allow failures if needed

```
environment:
  matrix:
  - nodejs_version: "0.10"
  - nodejs_version: "0.11"
  allow_failures:
  - nodejs_version: "0.12"
  # io.js
  - nodejs_version: "1.0"
```
