### ISSUE TITLE
A lost rule when extending inside a double for loop

### ISSUE THREAD

**Issue by mzgol** [jscs-dev/node-jscs#1228]
The following SCSS:
```scss
@for $i from 1 through 2 {
    %shift-#{$i - 1} {
        margin-left: $i * 1px;
    }
    .week-start-#{$i} {
        @for $j from 1 through 2 {
            .month-start-#{$j} {
                @extend %shift-#{($j - $i - 1) % 2};
            }
        }
    }
}
```
libsass from node-sass `3.0.0-beta.4` turns into:
```css
.week-start-1 .month-start-2, .week-start-2 .month-start-1 {
  margin-left: 1px; }
```
Latest Ruby Sass gives:
```css
.week-start-1 .month-start-2, .week-start-2 .month-start-1 {
  margin-left: 1px; }

.week-start-1 .month-start-1, .week-start-2 .month-start-2 {
  margin-left: 2px; }
```
